/*
 * Module 25: AI Chatbot Agent Demo
 *
 * Launches the ChatbotAgent as a subprocess and has a short conversation with
 * it, exactly like the echo agent demo (module 12) - but now the replies are
 * generated by Claude instead of echoed.
 *
 * Two things to notice vs. the echo demo:
 *   1. The update consumer uses System.out.print (no newline) so the streamed
 *      token chunks flow together into one response on screen.
 *   2. We send a follow-up prompt in the SAME session to show that the agent
 *      remembers the conversation (per-session history).
 *
 * Build & run (requires ANTHROPIC_API_KEY):
 *   ./mvnw package -pl module-25-ai-chatbot-agent -q
 *   ./mvnw exec:java -pl module-25-ai-chatbot-agent
 */
package com.acptutorial.module25;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import com.agentclientprotocol.sdk.client.AcpClient;
import com.agentclientprotocol.sdk.client.AcpSyncClient;
import com.agentclientprotocol.sdk.client.transport.AgentParameters;
import com.agentclientprotocol.sdk.client.transport.StdioAcpClientTransport;
import com.agentclientprotocol.sdk.spec.AcpSchema.AgentMessageChunk;
import com.agentclientprotocol.sdk.spec.AcpSchema.NewSessionRequest;
import com.agentclientprotocol.sdk.spec.AcpSchema.PromptRequest;
import com.agentclientprotocol.sdk.spec.AcpSchema.TextContent;

public class ChatbotAgentDemo {

    private static final String MODULE_NAME = "module-25-ai-chatbot-agent";
    private static final String JAR_NAME = "chatbot-agent.jar";

    public static void main(String[] args) {
        // Friendly pre-flight: the subprocess needs the key, so check it here too.
        if (System.getenv("ANTHROPIC_API_KEY") == null || System.getenv("ANTHROPIC_API_KEY").isBlank()) {
            System.err.println("ERROR: ANTHROPIC_API_KEY is not set. Export it before running this demo.");
            System.exit(1);
        }

        // Launch the ChatbotAgent as a subprocess using the packaged JAR.
        var params = AgentParameters.builder("java")
            .arg("-jar")
            .arg(findAgentJar())
            .build();

        var transport = new StdioAcpClientTransport(params);

        try (AcpSyncClient client = AcpClient.sync(transport)
                .sessionUpdateConsumer(notification -> {
                    var update = notification.update();
                    if (update instanceof AgentMessageChunk msg) {
                        // print (not println) so streamed chunks coalesce into one reply
                        System.out.print(((TextContent) msg.content()).text());
                        System.out.flush();
                    }
                })
                .build()) {

            System.out.println("=== Module 25: AI Chatbot Agent Demo ===\n");

            client.initialize();
            System.out.println("Connected to ChatbotAgent (powered by Claude)!\n");

            String cwd = System.getProperty("user.dir");
            var session = client.newSession(new NewSessionRequest(cwd, List.of()));

            // First question
            ask(client, session.sessionId(),
                "Write a haiku about debugging code.");

            // Follow-up in the SAME session - "that haiku" only makes sense if the
            // agent remembers the previous turn (per-session history).
            ask(client, session.sessionId(),
                "Now turn that haiku into a limerick.");

        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private static void ask(AcpSyncClient client, String sessionId, String question) {
        System.out.println("\nYou: " + question);
        System.out.print("Claude: ");
        var response = client.prompt(new PromptRequest(
            sessionId, List.of(new TextContent(question))));
        System.out.println("\n(stop reason: " + response.stopReason() + ")");
    }

    /**
     * Find the agent JAR whether running from repo root or module directory.
     */
    private static String findAgentJar() {
        Path fromModule = Path.of("target/" + JAR_NAME);
        if (Files.exists(fromModule)) {
            return fromModule.toString();
        }
        Path fromRoot = Path.of(MODULE_NAME + "/target/" + JAR_NAME);
        if (Files.exists(fromRoot)) {
            return fromRoot.toString();
        }
        throw new RuntimeException(
            "Agent JAR not found. Run: ./mvnw package -pl " + MODULE_NAME);
    }
}
