/*
 * Module 27: LangChain4j Chatbot Agent Demo
 *
 * Launches the LangChain4j chatbot agent as a subprocess and asks it a question.
 * Same pattern as module 25's demo; the reply is generated by Claude via
 * LangChain4j's ChatModel.
 *
 * Build & run (requires ANTHROPIC_API_KEY):
 *   ./mvnw package -pl module-27-langchain4j-chatbot -q
 *   ./mvnw exec:java -pl module-27-langchain4j-chatbot
 */
package com.acptutorial.module27;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import com.agentclientprotocol.sdk.client.AcpClient;
import com.agentclientprotocol.sdk.client.AcpSyncClient;
import com.agentclientprotocol.sdk.client.transport.AgentParameters;
import com.agentclientprotocol.sdk.client.transport.StdioAcpClientTransport;
import com.agentclientprotocol.sdk.spec.AcpSchema.AgentMessageChunk;
import com.agentclientprotocol.sdk.spec.AcpSchema.NewSessionRequest;
import com.agentclientprotocol.sdk.spec.AcpSchema.PromptRequest;
import com.agentclientprotocol.sdk.spec.AcpSchema.TextContent;

public class LangChain4jChatbotDemo {

    private static final String MODULE_NAME = "module-27-langchain4j-chatbot";
    private static final String JAR_NAME = "langchain4j-chatbot.jar";

    public static void main(String[] args) {
        if (System.getenv("ANTHROPIC_API_KEY") == null || System.getenv("ANTHROPIC_API_KEY").isBlank()) {
            System.err.println("ERROR: ANTHROPIC_API_KEY is not set. Export it before running this demo.");
            System.exit(1);
        }

        var params = AgentParameters.builder("java")
            .arg("-jar")
            .arg(findAgentJar())
            .build();

        var transport = new StdioAcpClientTransport(params);

        try (AcpSyncClient client = AcpClient.sync(transport)
                .sessionUpdateConsumer(notification -> {
                    var update = notification.update();
                    if (update instanceof AgentMessageChunk msg) {
                        System.out.print(((TextContent) msg.content()).text());
                        System.out.flush();
                    }
                })
                .build()) {

            System.out.println("=== Module 27: LangChain4j Chatbot Agent Demo ===\n");

            client.initialize();
            System.out.println("Connected to LangChain4j ChatbotAgent (powered by Claude)!\n");

            String cwd = System.getProperty("user.dir");
            var session = client.newSession(new NewSessionRequest(cwd, List.of()));

            String question = "In one sentence, what is LangChain4j?";
            System.out.println("You: " + question);
            System.out.print("Claude: ");
            var response = client.prompt(new PromptRequest(
                session.sessionId(), List.of(new TextContent(question))));
            System.out.println("\n(stop reason: " + response.stopReason() + ")");

        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private static String findAgentJar() {
        Path fromModule = Path.of("target/" + JAR_NAME);
        if (Files.exists(fromModule)) {
            return fromModule.toString();
        }
        Path fromRoot = Path.of(MODULE_NAME + "/target/" + JAR_NAME);
        if (Files.exists(fromRoot)) {
            return fromRoot.toString();
        }
        throw new RuntimeException(
            "Agent JAR not found. Run: ./mvnw package -pl " + MODULE_NAME);
    }

}
